GRAPHQL-13: Split a GQL AST representing a root GQL request into individual operations.
marklogic/marklogic-graphql pull request #10
Opened 2022-05-11 10:14 UTC by AndreiPanti

2022-05-11 10:52 UTC, mariusmarklogic approved these changes

2022-05-11 12:44 UTC, cpisoiu commented on src/main/ml-modules/root/mlGraphqlLibOpticApi.sjs
> +function buildArrayObject(queriesArray, mutationsArray, subscriptionsArray) {
I would move this above the previous function that is using it.

2022-05-11 13:09 UTC, AndreiPanti commented on src/main/ml-modules/root/mlGraphqlLibOpticApi.sjs
> +  if ((astObject.errors.length === 0) && (astObject.queryDocumentAst.kind === "Document")) {
If there is an error, it will be handled in the transformGraphqlIntoASTPlan function. If is not redundant, I can gladly add that check also in the tests for transformASTIntoArrayObject function.

2022-05-11 14:24 UTC, BillFarber commented on src/main/ml-modules/root/mlGraphqlLibOpticApi.sjs
> +function buildArrayObject(queriesArray, mutationsArray, subscriptionsArray) {
Let's not worry about function ordering for now.

2022-05-11 14:41 UTC, BillFarber requested changes

2022-05-11 14:41 UTC, BillFarber commented on src/test/ml-modules/root/test/suites/opticTransformer/individualOperationTest.sjs
> +);
Since you're comparing simple values, assertEqual would be more appropriate here:

  test.assertEqual("query", arrayObject["queries"][0].operation,
    "The resulting array object does not match the expected results."),
  test.assertEqual([], arrayObject["mutations"],
    "The resulting array object does not match the expected results."),
  test.assertEqual([], arrayObject["subscriptions"],
    "The resulting array object does not match the expected results.")

2022-05-11 14:41 UTC, BillFarber commented on src/test/ml-modules/root/test/suites/opticTransformer/individualOperationTest.sjs
> +);
See above comments.

2022-05-12 06:50 UTC, cpisoiu commented on src/main/ml-modules/root/mlGraphqlLibOpticApi.sjs
> +  if ((astObject.errors.length === 0) && (astObject.queryDocumentAst.kind === "Document")) {
Great.

2022-05-12 13:47 UTC, BillFarber approved these changes

2022-05-12 14:00 UTC, cpisoiu commented
Good to go

2022-05-12 14:00 UTC, cpisoiu approved these changes

2022-05-12 14:25 UTC, merged